<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Automation.Module.FormBuilder</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Automation.Core\Automation.Core.csproj" />
    <ProjectReference Include="..\Automation.Infrastructure\Automation.Infrastructure.csproj" />
  </ItemGroup>

</Project>
